---
# 6. GitLab (continued)

- hosts: gitlab
  sudo: yes
  tasks:
    - name: ensure init script is installed
      get_url: url=https://raw.github.com/gitlabhq/gitlab-recipes/4-2-stable/init.d/gitlab dest=/etc/init.d/gitlab mode=0755
    - name: make GitLab start on boot
      command: update-rc.d gitlab defaults 21
    - name: restart GitLab
      command: /etc/init.d/gitlab start && /bin/true

# 7. Nginx

- hosts: gitlab
  sudo: yes
  tasks:
    - name: ensure package nginx is present
      apt: state=present pkg=nginx
    - name: ensure GitLab Nginx site is available
      get_url: url=https://raw.github.com/gitlabhq/gitlab-recipes/4-2-stable/nginx/gitlab dest=/etc/nginx/sites-available/gitlab mode=0755
    - name: ensure default Nginx site is not enabled
      file: state=absent path=/etc/nginx/sites-enabled/default
    - name: ensure GitLab Nginx site is enabled
      file: state=link src=/etc/nginx/sites-available/gitlab path=/etc/nginx/sites-enabled/gitlab
